services:
  bot:
    build: .
    volumes:
      - ./bot:/usr/src/bot:rw
    env_file:
      - .env
    environment:
      - TZ=Asia/Tokyo
    command: ["python3", "card_recruitment.py"]
    restart: unless-stopped
    tty: true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
