services:
  bot:
    build: .
    volumes:
      - ./bot:/usr/src/bot:rw
    env_file:
      - .env
    environment:
      - TZ=Asia/Tokyo
    command: ["python3", "matching.py"]
    restart: unless-stopped
    tty: true
